Fix typos and refine wording
Code4PuertoRico/codeofconduct pull request #3
Opened 2020-03-02 21:30 UTC by marcmaceira

2020-03-03 01:22 UTC, froi requested changes
Gracias por darle un vistazo a esto y por arreglar mi ortografia! ❤️ 

Te deje una sugerencia. Un vez aceptada le podemos darle merge a este PR. 😉

2020-03-03 01:22 UTC, froi commented on README.md
> +  - [Cómo contribuir](#como-contribuir-a-este-código-de-conducta)
Se tiene que añadir acentos a los enlances una vez se le añade a los "headings".

```suggestion
  - [Cómo contribuir](#cómo-contribuir-a-este-código-de-conducta)
```

2020-03-03 13:09 UTC, marcmaceira commented
Gracias por el pointer!

2020-03-09 05:06 UTC, froi approved these changes

2020-03-09 05:06 UTC, merged